terraform {
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }
  }
}

# Create project folders simulating cloud infrastructure
resource "local_file" "dev_config" {
  filename = "${path.module}/infrastructure/dev/config.json"
  content  = jsonencode({
    environment     = "development"
    cloud_provider  = "AWS"
    region          = "ap-south-1"
    instance_type   = "t2.micro"
    auto_scaling    = true
    min_instances   = 1
    max_instances   = 5
    database        = "PostgreSQL"
    storage         = "S3"
    created_by      = "Terraform"
    created_at      = timestamp()
  })
}

resource "local_file" "prod_config" {
  filename = "${path.module}/infrastructure/prod/config.json"
  content  = jsonencode({
    environment     = "production"
    cloud_provider  = "AWS"
    region          = "ap-south-1"
    instance_type   = "t3.large"
    auto_scaling    = true
    min_instances   = 3
    max_instances   = 20
    database        = "PostgreSQL"
    storage         = "S3"
    created_by      = "Terraform"
    created_at      = timestamp()
  })
}

resource "local_file" "infrastructure_report" {
  filename = "${path.module}/infrastructure/report.md"
  content  = <<-EOT
    # 🏗️ Infrastructure Report
    Generated by Terraform automatically!
    
    ## Environments
    - ✅ Development: t2.micro | 1-5 instances
    - ✅ Production: t3.large | 3-20 instances
    
    ## Cloud Services
    - Region: ap-south-1 (Mumbai)
    - Database: PostgreSQL
    - Storage: S3
    - Auto Scaling: Enabled
    
    ## Status: DEPLOYED ✅
  EOT
}